// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a monetary value in the smallest currency unit (cents for USD).
 *
 * ## Design Decisions
 * - **i64 (signed)**: Allows negative values for refunds, discounts
 * - **Single field tuple struct**: Zero-cost abstraction over i64
 * - **Derives**: Full serde support for JSON serialization
 *
 * ## User Workflow Context
 * ```text
 * ┌─────────────────────────────────────────────────────────────────────────┐
 * │                    Where Money is Used                                  │
 * │                                                                         │
 * │  Product.price_cents ──┬──► CartItem.unit_price ──► CartItem.line_total │
 * │                        │                                                │
 * │                        └──► Displayed as "$10.99" in UI                 │
 * │                                                                         │
 * │  Cart.subtotal ──► Tax Calculation ──► Cart.total ──► Payment.amount   │
 * │                                                                         │
 * │  EVERY monetary value in the system flows through this type            │
 * └─────────────────────────────────────────────────────────────────────────┘
 * ```
 */
export type Money = bigint;
