// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaymentMethod } from "./PaymentMethod";

/**
 * A payment towards a sale.
 * A sale can have multiple payments for split tender scenarios.
 */
export type Payment = { id: string, sale_id: string, method: PaymentMethod, 
/**
 * Amount paid in cents.
 */
amount_cents: bigint, 
/**
 * For cash: amount customer gave (to calculate change).
 */
tendered_cents: bigint | null, 
/**
 * For cash: change returned to customer.
 */
change_cents: bigint | null, 
/**
 * External reference (card auth code, etc.).
 */
reference: string | null, created_at: string, };
