// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A product available for sale.
 */
export type Product = { 
/**
 * Unique identifier (UUID v4).
 */
id: string, 
/**
 * Tenant this product belongs to.
 */
tenant_id: string, 
/**
 * Stock Keeping Unit - business identifier.
 */
sku: string, 
/**
 * Barcode (EAN-13, UPC-A, etc.).
 */
barcode: string | null, 
/**
 * Display name shown to cashier and on receipt.
 */
name: string, 
/**
 * Optional description for product details.
 */
description: string | null, 
/**
 * Price in cents (smallest currency unit).
 */
price_cents: bigint, 
/**
 * Cost in cents (for profit margin calculations).
 */
cost_cents: bigint | null, 
/**
 * Tax rate in basis points (825 = 8.25%).
 */
tax_rate_bps: number, 
/**
 * Whether to track inventory for this product.
 */
track_inventory: boolean, 
/**
 * Allow selling when stock is zero or negative.
 */
allow_negative_stock: boolean, 
/**
 * Current stock level.
 */
current_stock: bigint | null, 
/**
 * Whether product is active (soft delete).
 */
is_active: boolean, 
/**
 * When the product was created.
 */
created_at: string, 
/**
 * When the product was last updated.
 */
updated_at: string, 
/**
 * Sync version for CRDT conflict resolution.
 */
sync_version: bigint, };
