// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A line item in a sale.
 * Uses snapshot pattern to freeze product data at time of sale.
 */
export type SaleItem = { id: string, sale_id: string, product_id: string, 
/**
 * SKU at time of sale (frozen).
 */
sku_snapshot: string, 
/**
 * Product name at time of sale (frozen).
 */
name_snapshot: string, 
/**
 * Unit price in cents at time of sale (frozen).
 */
unit_price_cents: bigint, 
/**
 * Quantity sold.
 */
quantity: bigint, 
/**
 * Line total before tax (unit_price × quantity).
 */
line_total_cents: bigint, 
/**
 * Tax for this line item.
 */
tax_cents: bigint, 
/**
 * Discount applied to this line.
 */
discount_cents: bigint, created_at: string, };
