// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SaleStatus } from "./SaleStatus";

/**
 * A completed or in-progress sale transaction.
 */
export type Sale = { id: string, tenant_id: string, receipt_number: string, status: SaleStatus, subtotal_cents: bigint, tax_cents: bigint, discount_cents: bigint, total_cents: bigint, user_id: string, device_id: string, notes: string | null, created_at: string, updated_at: string, completed_at: string | null, sync_version: bigint, };
