// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An entry in the sync outbox queue.
 * Uses outbox pattern for reliable sync with cloud.
 */
export type SyncOutboxEntry = { id: string, tenant_id: string, 
/**
 * Type of entity being synced: "SALE", "PRODUCT", "PAYMENT", etc.
 */
entity_type: string, 
/**
 * ID of the entity being synced.
 */
entity_id: string, 
/**
 * The full entity data as JSON.
 */
payload: string, 
/**
 * Number of sync attempts.
 */
attempts: bigint, 
/**
 * Last error message if sync failed.
 */
last_error: string | null, created_at: string, 
/**
 * When last sync was attempted.
 */
attempted_at: string | null, 
/**
 * When successfully synced.
 */
synced_at: string | null, };
