// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Tax rate represented in basis points (bps).
 *
 * ## Why Basis Points?
 * 1 basis point = 0.01% = 1/10000
 * 825 bps = 8.25% (e.g., Texas sales tax)
 */
export type TaxRate = number;
