//! Generated Protocol Buffer code.
//!
//! This module contains the generated Rust code from the .proto files.
//! The code is generated by tonic-build during the build process.

// `Notification::Payload` is a prost `oneof` whose variants differ in size by
// more than clippy's threshold. The shape is dictated by titan_sync.proto and
// the code is regenerated on every build, so it cannot be edited here.
#![allow(clippy::large_enum_variant)]

// Include the generated code from $OUT_DIR
tonic::include_proto!("titan.sync.v1");
