//! Generated Protocol Buffer code.
//!
//! This module contains the generated Rust code from the .proto files.
//! The code is generated by tonic-build during the build process.

// Include the generated code from $OUT_DIR
tonic::include_proto!("titan.sync.v1");
